@extends('admin/layout/main')
@section('productCreatePage')
    <!-- MAIN CONTENT-->
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible fade show col-3 offset-9" role="alert">
                        <strong>{{ session('success') }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                <div class="col-lg-6 offset-3">
                    {{-- @if (count($categories) != 0) --}}
                    <div class="card">
                        <div class="card-body">
                            <i class="fa-solid fa-arrow-left text-primary" onclick="history.back()"></i>
                            <div class="card-title">
                                <h3 class="text-center title-2">Product Form</h3>
                            </div>
                            <hr>
                            <form action="{{ route('productCreate') }}" method="post" novalidate="novalidate"
                                enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="name" class="control-label mb-1">Name</label>
                                    <input id="name" name="name" type="text" class="form-control"
                                        aria-required="true" aria-invalid="false" placeholder="Enter product name">
                                    @error('name')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="image" class="control-label mb-1">Image</label>
                                    <input type="file" name="image" class="form-control" id="image">
                                    @error('image')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="sideImage1" class="control-label mb-1">first page image</label>
                                    <input type="file" name="sideImage1" class="form-control" id="sideImage1">
                                    @error('sideImage1')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="sideImage2" class="control-label mb-1">second page image</label>
                                    <input type="file" name="sideImage2" class="form-control" id="sideImage2">
                                    @error('sideImage2')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group" style="position: relative;">
                                    <label for="arthur" class="control-label mb-1">Arthur</label>
                                    <input type="text" name="arthur" class="form-control mainCati" id="arthur">
                                    <div class="suggestBoxAr"
                                        style="background-color: white;visibility:hidden; max-height: 100px; width: 100%; overflow-y: auto; position: absolute; z-index: 3;">
                                        <!-- Content dynamically generated by JavaScript -->
                                    </div>
                                    @error('arthur')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group" style="position: relative;">
                                    <label for="mainCategory" class="control-label mb-1">Main Category</label>
                                    <select name="mainCategoryId" class="form-control" id="mainCategory">
                                        @foreach ($mainCategories as $c)
                                            <option value="{{ $c['id'] }}">{{ $c['name'] }}</option>
                                        @endforeach
                                    </select>
                                    {{-- <input type="text" name="mainCategory" class="form-control mainCati"
                                        id="mainCategory">
                                    <div class="suggestBoxMain"
                                        style="background-color:white;visibility:hidden;max-height:100px;width:100%;overflow:scroll;overflow-x:hidden;position:absolute;z-index:3;">
                                    </div> --}}
                                    @error('mainCategory')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror

                                </div>
                                <div class="form-group">
                                    <label for="category" class="control-label mb-1">Category</label>
                                    <select name="categoryId" class="form-control" id="category">
                                        @foreach ($categories as $c)
                                            <option value="{{ $c['id'] }}">{{ $c['name'] }}</option>
                                        @endforeach
                                    </select>
                                    {{-- <input type="text" name="category" class="form-control cati" id="category">
                                    <div class="suggestBoxCati"
                                        style="background-color:white;visibility:hidden;max-height:100px;width:100%;overflow:scroll;overflow-x:hidden;position:absolute;z-index:3;">
                                    </div> --}}
                                    @error('category')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <div class="checkBoxContainer" style="display: flex;justify-content:space-between">
                                        <div class="checkBox">
                                            <label for="editorChoice">Editor Choice</label>
                                            <input type="hidden" name="editorChoice" value="False">
                                            <input type="checkbox" name="editorChoice" id="editorChoice" value="True">
                                        </div>
                                        <div class="checkBox">
                                            <label for="reward">Reward</label>
                                            <input type="hidden" name="reward" value="False">
                                            <input type="checkbox" name="reward" id="reward" value="True">
                                        </div>
                                        <div class="checkBox">
                                            <label for="classic">Classic</label>
                                            <input type="hidden" name="classic" value="False">
                                            <input type="checkbox" name="classic" id="classic" value="True">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" style="position: relative;">
                                    <label for="readingGuide" class="control-label mb-1">Reading Guide</label>
                                    {{-- <select name="readingGuideId" class="form-control" id="readingGuide">
                                        @foreach ($mainCategories as $c)
                                            <option value="{{$c['id']}}">{{$c['name']}}</option>
                                        @endforeach
                                    </select> --}}
                                    <input type="text" name="readingGuide" class="form-control mainCati"
                                        id="readingGuide">
                                    <div class="suggestBoxRg"
                                        style="background-color:white;visibility:hidden;max-height:100px;width:100%;overflow:scroll;overflow-x:hidden;position:absolute;z-index:3;">
                                    </div>
                                    @error('readingGuide')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="description" class="control-label mb-1">Description</label>
                                    <textarea name="description" id="description" class="form-control" placeholder="Enter product description"
                                        cols="30" rows="10"></textarea>
                                    @error('description')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="pages" class="control-label mb-1">Pages</label>
                                    <input id="pages" name="pages" type="number" class="form-control"
                                        aria-required="true" aria-invalid="false" placeholder="Enter product pages">
                                    @error('pages')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="printRecord" class="control-label mb-1">Print Record</label>
                                    <input id="printRecord" name="printRecord" type="text" class="form-control"
                                        aria-required="true" aria-invalid="false"
                                        placeholder="Enter product printRecord">
                                    @error('printRecord')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group" style="position: relative;">
                                    <label for="size" class="control-label mb-1">Book size</label>
                                    {{-- <select name="sizeId" class="form-control" id="size">
                                        @foreach ($mainCategories as $c)
                                            <option value="{{$c['id']}}">{{$c['name']}}</option>
                                        @endforeach
                                    </select> --}}
                                    <input type="text" name="size" class="form-control mainCati" id="size">
                                    <div class="suggestBoxBs"
                                        style="background-color:white;visibility:hidden;max-height:100px;width:100%;overflow:scroll;overflow-x:hidden;position:absolute;z-index:3;">
                                    </div>
                                    @error('size')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror

                                </div>
                                <div class="form-group">
                                    <label for="inStock" class="control-label mb-1">instock</label>
                                    <input id="inStock" name="inStock" type="number" class="form-control"
                                        aria-required="true" aria-invalid="false" placeholder="Enter inStock">
                                    @error('inStock')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="price" class="control-label mb-1">Price</label>
                                    <input id="price" name="price" type="number" class="form-control"
                                        aria-required="true" aria-invalid="false" placeholder="Enter product price">
                                    @error('price')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <span id="payment-button-amount">Create</span>
                                        <span id="payment-button-sending" style="display:none;">Sending…</span>
                                        <i class="fa-solid fa-circle-right"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    {{-- @else
                                <div class=" d-flex justify-content-center align-items-center col-12 mt-5">
                                    <h1>create category first!</h1>
                                </div>
                            @endif --}}
                </div>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT-->

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const arthurInput = document.querySelector('#arthur');
            const suggestBoxAr = document.querySelector('.suggestBoxAr');
            const arthurs = <?php echo json_encode($arthurs); ?>;

            arthurInput.addEventListener('input', function(event) {
                handleInputEvent(event, arthurInput, suggestBoxAr, arthurs);
            });

            const sizeInput = document.querySelector('#size');
            const suggestBoxBs = document.querySelector('.suggestBoxBs');
            const bookSizes = <?php echo json_encode($bookSizes); ?>;

            sizeInput.addEventListener('input', function(event) {
                handleInputEvent(event, sizeInput, suggestBoxBs, bookSizes);
            });

            const readingGuideInput = document.querySelector('#readingGuide');
            const suggestBoxRg = document.querySelector('.suggestBoxRg');
            const readingGuides = <?php echo json_encode($readingGuides); ?>;

            readingGuideInput.addEventListener('input', function(event) {

                handleInputEvent(event, readingGuideInput, suggestBoxRg, readingGuides);
            });

            function handleInputEvent(event, inputField, suggestBox, options) {
                const inputValue = event.target.value.toLowerCase();
                suggestBox.innerHTML = '';

                options.forEach(function(option) {
                    // Ensure option is a string
                    if (typeof option === 'string') {
                        const optionValue = option.toLowerCase();

                        if (optionValue.includes(inputValue)) {
                            const itemDiv = document.createElement('div');
                            itemDiv.classList.add('item');
                            itemDiv.style.padding = '5px';
                            itemDiv.style.cursor = 'pointer';
                            itemDiv.textContent = option;

                            itemDiv.addEventListener('click', function() {
                                inputField.value = option;
                                suggestBox.style.visibility = 'hidden';
                            });


                            suggestBox.appendChild(itemDiv);

                        }
                    }
                });

                suggestBox.style.visibility = inputValue.length > 0 ? 'visible' : 'hidden';
            }
        });
    </script>
@endsection
